ALTER TABLE tasks
    ADD COLUMN IF NOT EXISTS start_time DATETIME NOT NULL,
    ADD COLUMN IF NOT EXISTS end_time DATETIME,
    ADD COLUMN IF NOT EXISTS priority VARCHAR(50),
    ADD COLUMN IF NOT EXISTS is_completed BOOLEAN NOT NULL DEFAULT FALSE; 